name: Build and Deploy to Compute Engine

on:
  push:
    branches: [ "trunk" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: us-central1
  GCE_LOCATION: us-central1
  GCE_ZONE: us-central1-a
  INSTANCE_NAME: ticonderoga-bot
  TEMPLATE_NAME: ticonderoga
  REPOSITORY: ticonderoga
  IMAGE: ticonderoga-bot

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/962511402854/locations/global/workloadIdentityPools/ticonderoga/providers/ticonderoga-provider'
        service_account: 'ticonderoga-svc-acct@key-chalice-390220.iam.gserviceaccount.com'

    - name: 'Set up gcloud CLI'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish Image
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

    # Create VM if it doesn't exist
    - name: Create VM instance
      run: |-
        gcloud compute instances describe $INSTANCE_NAME --zone=$GCE_ZONE --format=none || \
        gcloud compute instances create $INSTANCE_NAME \
          --source-instance-template $TEMPLATE_NAME \
          --zone $GCE_ZONE

    # Update container image
    - name: Update container image
      run: |-
        gcloud compute instances update-container $INSTANCE_NAME \
          --container-image "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --zone=$GCE_ZONE